language: csharp
solution: GraphApplication.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore WpfGraph.sln
  
script:
  - xbuild /p:Configuration="TravisEnvironment" WpfGraph.sln
  - nunit-console ./GraphTests/bin/TravisEnvironment/Wpf/GraphTests.dll
